import mongoose from "mongoose";
const CompanySchema=new mongoose.Schema({
    companyName:{
        type:String
    },
    email:{
        type:String
    },
    password:{
        type:String
    },
    contactNumber:{
        type:Number
    },
    typeOfCompany:{
        type:String
    },
    companyDescription:{
        type:String
    },
    website:{
        type:String
    },
    logo:{
        type:String
    },
    establishedYear:{
        type:String
    },
    headQuarters:{
        type:String
    },
    socialMedia:{
        linkedin:{
            type:String
        },
        twitter:{
            type:String
        },
        facebookd:{
            type:String
        }
    },
    ceoName:{
        type:String
    },
    missionStatement:{
        type:String
    },
    companyaddress:[{
        id:{
            type:String,
        },
        Buildingname:{
            type:String,
        },
        area:{
            type:String,
        },
        street:{
            type:String,
        },
        pincode:{
            type:Number,
        },
        city:{
            type:String,
        },
        state:{
            type:String,
        },
        country:{
            type:String
        },
    }],
    numberOfEmployees:{
        type:Number
    },
    reviewsId:[{
        type:mongoose.Schema.ObjectId,
        ref:'Review'
    }]
},{
    timestamps:true
})
export const Company=mongoose.model('Company',CompanySchema)