import mongoose from "mongoose";

const ResumeSchema=new mongoose.Schema({
    name:{
        type:String
    },
    email:{
        type:String
    },
    contact:{
        type:Number
    },
    address:[{
        id:{
            type:String,
        },
        Housename:{
            type:String,
        },
        area:{
            type:String,
        },
        street:{
            type:String,
        },
        pincode:{
            type:Number,
        },
        city:{
            type:String,
        },
        state:{
            type:String,
        },
        country:{
            type:String
        },
    }],
    education:[
        {
        levelOfEducation:{
            type:String,
        },
        degree:{
            type:String
        },
        specialization:{
            type:String
        },
        city:{
            type:String
        },
        state:{
            type:String
        },
        country:{
            type:String
        },
        collegeName:{
            type:String
        },
        startDate:{
            type:Date
        },
        endDate:{
            type:Date
        },
        courseType:{
            type:String
        },
        percentage:{
            type:Number
        }
    },
],
skills:{
    type:[]
},
candidate:{
    type:mongoose.Schema.Types.ObjectId,
        ref:'User'
}
},
{
    timestamps:true
})
export const Resume=mongoose.model('Resume',ResumeSchema)